export const SET_CAROUSEL = 'SET_CAROUSEL';

export const SET_DANH_SACH_PHIM = 'SET_DANH_SACH_PHIM';

export const SET_HE_THONG_RAP_CHIEU = 'SET_HE_THONG_RAP_CHIEU';

export const SET_CUM_RAP_THEO_HE_THONG = 'SET_CUM_RAP_THEO_HE_THONG';
